name: Fuzz

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: read

concurrency:
  group: fuzz-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fuzz:
    uses: getquario/meta/.github/workflows/fuzz.yml@main
    with:
      targets: '["compile","evaluate","structured"]'
